package interviewsKdn251.Company.Google;

/**
 * Created by user on 25.04.2017.
 */
// Given two strings s and t which consist of only lowercase letters.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Find the letter that was added in t.

// Example:

// Input:
// s = "abcd"
// t = "abcde"

// Output:
// e

// Explanation:
// 'e' is the letter that was added.
public class FindTheDifference {

    public static char  findDifference(String t, String s){
        int countT = 0;

        for (int i = 0; i < t.length(); i++){
            countT += (int) t.charAt(i);
        }

        int countS = 0;
        for (int i = 0; i < s.length(); i++){
            countS += (int) s.charAt(i);
        }

        return (char)(countT - countS);
    }
}
